### ISSUE TITLE
Link behavior ignores sorted date time order

### ISSUE THREAD

**Issue by snapperlux** [Microsoft/charticulator#103]
Add a simple running data set (Date Time and HR BPM):
![screenshot 339](https://user-images.githubusercontent.com/43861167/46773096-725fee00-ccb0-11e8-9b2e-e529eedb63cc.png)

Add  circle mark to glyph panel. Datetime to X Axis and BPM to Y Axis:
![screenshot 343](https://user-images.githubusercontent.com/43861167/46773135-aaffc780-ccb0-11e8-8871-8dbcd8f4044b.png)

Add a link to draw a line plot:
![screenshot 344](https://user-images.githubusercontent.com/43861167/46773151-b3f09900-ccb0-11e8-9d5f-adcf54656531.png)

Result:
![screenshot 340](https://user-images.githubusercontent.com/43861167/46773164-c4087880-ccb0-11e8-9aa8-5a3dce4e3d65.png)

The order is correct in regards to the data set as the gyphs plot correctly. But the links do not acknowledge the correct order. I have tried with different date time format variations and still get the same result. Perhaps I am missing something?

Data sample below:
[Morning.txt](https://github.com/Microsoft/charticulator/files/2466889/Morning.txt)

**Comment by donghaoren** [comment]
Right now Charticulator only links the data in the order they appear in the table, and we don't have an option to change that yet. It appears that your `Datetime` column is not sorted, could you try sorting them and see if it works? The axis appears correct because by default a categorical axis is sorted alphabetically.

In addition, the `Datetime` column is not recognized as DateTime values because Charticulator accepts only a few formats right now, as below:

- DateTime: DateFormat TimeForamt TimezoneFormat
- DateFormats:
  - YYYY-MM, YYYY-MM-DD
  - MM/YYYY, MM/DD/YYYY
- TimeFormats:
  - HH:MM, HH:MM:SS
  - HH:MM{am/pm}, HH:MM:SS{am/pm}
- TimezoneFormat:
  - +HH:MM, -HH:MM

If you convert the `Datetime` column from `2018-09-09 22:50:31.000` to `2018-09-09 22:50:31` it should load as DateTime values, and the axis will appear as a datetime axis.

**Comment by snapperlux** [comment]
Yep, I tried sorting within Charticulator and doesn't seem to have an effect on links. I sorted externally brought it back on and linking order is correct!  Thanks!
