### ISSUE TITLE
Data Axis does not lock to a guide when exported to a PBIVIZ

### ISSUE THREAD

**Issue by snapperlux** [Microsoft/charticulator#106]
As you can see in the below picture I have 2 "Data Axis" from the original plot on the left side.
![screenshot 366](https://user-images.githubusercontent.com/43861167/47529736-803f7280-d85d-11e8-9125-d919fe659195.png)

When exported to PowerBI (using the same data set) the 2 "Data Axis" snap back to the center guide:

![screenshot 367](https://user-images.githubusercontent.com/43861167/47529798-b0871100-d85d-11e8-813b-0308b7f8025a.png)

**Comment by donghaoren** [comment]
This is a bug, guides are not retaining their original positions when exported into a visual. If you want to make a working visual before we fix it, you can use this hack:
- Add two rects between the three vertical guides (i.e., one between the blue and red, another one between the red and green). The rects should be snapped to the guides.
- Set the width of the rects to a desired value by selecting the rect and entering a number in its "width" attribute. If a rect is snapped correctly, setting its width will affect the position of the guide (because Charticulator uses a constraint-based layout algorithm!)
- Make the rect invisible by setting its opacity to 0, or simply remove the stroke and fill colors.

**Comment by snapperlux** [comment]
I tried this but it doesn't seem to fix anything when i output:
Add a rectangle shape between both data guides:

![image](https://user-images.githubusercontent.com/43861167/47687377-244a5600-db9d-11e8-99c7-0f65999640af.png)

I resized the width of the rectangles to 2px  then snapped to the guides:

![image](https://user-images.githubusercontent.com/43861167/47687400-4e9c1380-db9d-11e8-991c-a42bca8782f7.png)

When i export the 2 guides still snap back to center in PBI.

**Comment by donghaoren** [comment]
For this to work, the rectangle should be snapped to both _vertical_ guides:

![image](https://user-images.githubusercontent.com/1595237/47687609-4395b300-db9e-11e8-9dd1-1be51ab6edc3.png)

**Comment by snapperlux** [comment]
Neither was successful for me upon export to PBIVIZ. I did notice you are using a "plot segment" instead of a "data axis" to create the additional Y axis. I tried both and they both snap back to center. Essentially I am creating a multiple Y axis line chart and i want the Y axis to have independent scales.  

My steps: 
1. Create initial 2D plot segment with datetime field for X axis and measure 1 for Y axis.
![screenshot 381](https://user-images.githubusercontent.com/43861167/47696520-591dd380-dbc4-11e8-8c16-840534874a61.png)

2. Next, I add another glyph and create a second 2 D plot overlaying the first one. Add the same date time field on the X axis but another measure for the Y axis. Add a circle mark to the glyph panel and then hide the Y and X axis labels. Last I added a vertical guide to the left of the plots.
![screenshot 382](https://user-images.githubusercontent.com/43861167/47696560-97b38e00-dbc4-11e8-8cc2-946616b0e114.png)

3. Add a rectangle between the new vertical guide and the left most guide for the two 2D plots.
![screenshot 383](https://user-images.githubusercontent.com/43861167/47696620-d8130c00-dbc4-11e8-9774-dfc297b93203.png)
4. Make the rectangle transparent.
![screenshot 384](https://user-images.githubusercontent.com/43861167/47696629-e3663780-dbc4-11e8-9289-a3a32cf33655.png)

5. Add a data axis snapped to the left most vertical guide.
![screenshot 385](https://user-images.githubusercontent.com/43861167/47696658-01339c80-dbc5-11e8-9181-ae554a5532e7.png)


6. Output to PBI
![screenshot 386](https://user-images.githubusercontent.com/43861167/47696669-0ee92200-dbc5-11e8-92be-cb228fe0c2df.png)

Appreciate the help here! Very happy you are still developing this tool!

**Comment by donghaoren** [comment]
Could you try setting the width of the rectangle manually? i.e., enter something like 100 to its "Width" attribute.

**Comment by snapperlux** [comment]
Ok it works now! I followed the same steps as detailed above but after i snapped the rectangle to the two guides I then entered "100" manually to the width as you mentioned.

![screenshot 387](https://user-images.githubusercontent.com/43861167/47734975-b77c9d80-dc28-11e8-8d59-96b2a7bc038f.png)

Thanks!

**Comment by donghaoren** [comment]
Technically, you can extract the zip file. But I don't think it would be helpful, because it's doesn't resemble any visualization code you'd expect (e.g., something written with D3), so it would be very hard to modify.

I'd vote for an alternative way -- adding a popup Charticulator editor from Power BI so you can adjust the visualization after you've put data into it. We'll look into this possibility, but can't promise it can be implemented...

**Comment by bongshin** [comment]
I'm closing this issue because there is no further discussion.
