### ISSUE TITLE
unexpected and confusing data field “Granularity (Level of Detail)” in PowerBI desktop app

### ISSUE THREAD

**Issue by jcridgeNATS** [microsoft/charticulator#168]
I managed to successfully reproduce the video tutorial for the sideways histogram with error bars at http://charticulator.com/tutorials/tutorial9.html
 
However, after I exported the custom visual to use in the PBI desktop app, I get the following complication:
 
1)      unexpected and confusing data field appears “Granularity (Level of Detail)” 
 
Whilst a related video example also shows this new field at http://charticulator.com/tutorials/tutorial8.html#timeStart=32.87  it doesn’t on the face of it seem to make any sense or have a purpose. I may be wrong but it also didn’t seem to appear in the list of fields during the charticulator PBI Export process.

**Comment by bongshin** [comment]
Please try to use the [Charticulator Visual](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200002793?tab=Overview). The Power BI extension of Charticulator, which is a different codebase, is **_not_** actively maintained. Because we are a small team and have limited development resources, we focus on improving the Charticulator visual.

To learn how to get started, visit the [Charticulator Visual page](https://charticulator.com/docs/charticulator-visual.html).
