### ISSUE TITLE
loss of bar chart width after export to desktop PBI

### ISSUE THREAD

**Issue by jcridgeNATS** [microsoft/charticulator#169]
I managed to successfully reproduce the video tutorial for the sideways histogram with error bars at http://charticulator.com/tutorials/tutorial9.html
 
However, after I exported the custom visual to use in the PBI desktop app, the bars loose the original design width.
There also does not seem to be any way of editing the width in the desktop GUI

**Comment by jcridgeNATS** [comment]
Someone else has noted that they were not able to get an exported visual to work properly in PBI

https://dataviz.love/2018/12/20/dataviztools/

"Even though I could create a custom visual type that I exported, I could not make it work in Power BI no matter how I tried. I assume that is a limitation of PBI that sometimes there are simply too many marks up on the chart that have no equivalents in Power BI that it is not possible to replicate the same visual output – but I might be wrong here. Even if it is possible to do what I tried, it is not trivial to do so, that is for sure."

**Comment by bongshin** [comment]
Please try to use the [Charticulator Visual](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200002793?tab=Overview). The Power BI extension of Charticulator, which is a different codebase, is **_not_** actively maintained. Because we are a small team and have limited development resources, we focus on improving the Charticulator visual.

To learn how to get started, visit the [Charticulator Visual page](https://charticulator.com/docs/charticulator-visual.html).
