### ISSUE TITLE
Link is drawn under the bars for a combo chart

### ISSUE THREAD

**Issue by bongshin** [microsoft/charticulator#193]
For a combo chart (combining a bar chart and a line chart), the link is drawn under the bars.
![image](https://user-images.githubusercontent.com/9288805/74059625-3ff5fc00-499d-11ea-8358-15b08351f56c.png)

**Comment by Hasanul7898** [comment]
<img width="818" alt="Screenshot (15)" src="https://user-images.githubusercontent.com/60961632/74323303-54763200-4dab-11ea-9815-584b98fa8374.png">

In Layers, We can just Drag down the link below the plot segment and the legend

**Comment by digital-mining1** [comment]
Thanks for the tip @Hasanul7898 . Till now I was having to delete and redo the Charticulator Glyph objects in order to get around this issue. Basically, the objects are placed on top of each other in the order that they are created (i.e. oldest in back, most recent on top).  And this placement can be changed by just dragging and dropping them to the right order the 'Layers' window for desired effect. 
I think that this issue can be closed after capturing the above comment in the help documention.
