### ISSUE TITLE
Saving Power BI file optimized for Report server containing Charticulator Visuals fails

### ISSUE THREAD

**Issue by julmoser** [microsoft/charticulator#208]
I just developed a custom visual in Charticulator and wanted to test it now in Power BI Desktop optimized for Report Server. 
Before I add the custom visual there's no issue to save the file containing the data sources, however whenever I add the custom visual the error "Unable to save document. [directory] isn't a valid file path" appears: 
![image](https://user-images.githubusercontent.com/38879526/77523213-b2efff00-6e85-11ea-9d59-2040d6337f18.png)

I am using PBI desktop optimized for RS September 2019 version

**Comment by zBritva** [comment]
Hello @julmoser , it seems similar to https://github.com/microsoft/charticulator/issues/188#issuecomment-565636716

**Comment by bongshin** [comment]
I'm closing this issue because there is no further discussion.

Please try to use the [Charticulator Visual](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200002793?tab=Overview). The Power BI extension of Charticulator, which is a different codebase, is **_not_** actively maintained. Because we are a small team and have limited development resources, we focus on improving the Charticulator visual.

To learn how to get started, visit the [Charticulator Visual page](https://charticulator.com/docs/charticulator-visual.html).
