### ISSUE TITLE
How to verify the performance and safety of a component made in Charticulator for publication in Power BI

### ISSUE THREAD

**Issue by nadiafank** [microsoft/charticulator#227]
When we download the PBiz we get only the data call (json), not the component code. 
Do you recommend any procedure to validate that code? When designing it with Charticulator, supported by Microsoft, do you consider it valid?

**Comment by zBritva** [comment]
Hello @nadiafank , Do you want to pass certification, described in the article?: https://docs.microsoft.com/power-bi/developer/visuals/power-bi-custom-visuals-certified?

**Comment by nadiafank** [comment]
Hi @zBritva , Is it possible to pass that certification with a component made in Charticulator?

**Comment by zBritva** [comment]
@nadiafank I don't think, that it is possible. Because, 

1. Rule requires to use [tools](https://github.com/Microsoft/powerbi-visuals-tools):
https://docs.microsoft.com/power-bi/developer/visuals/power-bi-custom-visuals-certified#compiling-requirements

2. Part of charticulator works in the visual built by charticulator, Power BI Teams have to certify the code of charticulator too. It's pretty hard work.

3. For certification, the visual should be published in [AppSource](https://docs.microsoft.com/en-us/power-bi/developer/visuals/office-store) - it requires to support IE11 browser. *Maybe, they changed that rule.* IDK
And charticulator [uses WASM](https://caniuse.com/#feat=wasm), it's not supported by IE11 

**Contact with Power BI Visuals team, to get proper answer.** You can [find the support email in the documentation page](https://docs.microsoft.com/power-bi/developer/visuals/power-bi-custom-visuals-faq#how-to-get-support)

**Comment by nadiafank** [comment]
@zBritva , 
Thank you for your answer and links 

However I think there is an empty space that I hope can be attended by Microsoft

1) That Microsoft generates documentation or special processes to validate the performance and security of a component generated in Charticulator

Or, better yet,
2) Integrate Charticulator into the Power Bi tool panel

I will contact Power BI Visuals team

**Comment by bongshin** [comment]
I'm closing this issue because the latest Charticulator visual (Version 1.4.1) is certified and the Power BI extension of Charticulator is not actively maintained.
