### ISSUE TITLE
Set up charticulator.com website and build/deployment process

### ISSUE THREAD

**Issue by darthtrevino** [Microsoft/charticulator#3]

**Comment by MikeCarlo** [comment]
I was able to follow the steps listed in the [Readme file](https://github.com/Microsoft/charticulator/blob/master/README.md).  Everything was able to work until i got to the Yarn Build step.  I am getting an error:
fatal: not a git repository (or any of the parent directories): .git
webpack(7504) C:\Users\<User>\Desktop\charticulator-master\charticulator-master\node_modules\webpack-cli\bin\cli.js:244
webpack(7504)                           throw err;
webpack(7504)                           ^
webpack(7504)
webpack(7504) Error: Command failed: git rev-parse HEAD
webpack(7504) fatal: not a git repository (or any of the parent directories): .git

not sure why it is choking on the .git file, but it seems to fail the build because of this file.  
Any Suggestions?

**Comment by donghaoren** [comment]
Hi Mike,

> FYI, I downloaded the code as a zip file from Github.

The build process does require a `git clone` of the repository.
We'll document this in the README file.

**Comment by MikeCarlo** [comment]
thanks, it is now working and building.  Appreciate the fix.

**Comment by bongshin** [comment]
This is setup by @stopyoukid.
