### ISSUE TITLE
slow response and radius column option after scafolds not shown.

### ISSUE THREAD

**Issue by Timlee123** [microsoft/charticulator#389]
Hello, I have been having this issue for the last couple of days, and tried using chrom and ie. neither worked. is the website under redevelopment or maintenance? Thanks

**Comment by zBritva** [comment]
@Timlee123 Could you describe the problem in detail? Screenshoots, *.gif can be useful for figure out the problem. Thanks!

**Comment by Timlee123** [comment]
![image](https://user-images.githubusercontent.com/65834834/105248608-cdd8f000-5bca-11eb-9293-ddc5eb8f4d50.png)
![image](https://user-images.githubusercontent.com/65834834/105248706-f8c34400-5bca-11eb-98cf-336df0f85519.png)

**Comment by Timlee123** [comment]
thanks for your help. see the far right, that's where I can reach, the radius column option is not there. is this something I have done wrong?

**Comment by zBritva** [comment]
@Timlee123 do you mean that you can't click on Scaffolds buttons:

![image](https://user-images.githubusercontent.com/10897951/105249399-1c659a80-5b89-11eb-9a8c-1189f199043d.png)

because the screen  size is small?

Is yes then try to use "Zoom out" as temp solution

![image](https://user-images.githubusercontent.com/10897951/105249599-69497100-5b89-11eb-91fa-1263b7f35d23.png)

**Comment by Timlee123** [comment]
![image](https://user-images.githubusercontent.com/65834834/105249740-b3077b00-5bcc-11eb-81a8-8e44f91a1b7e.png)
yes, thank you. I zoomed out and can see it. love it when the issue is easily fixed. Thank you

**Comment by bongshin** [comment]
The recent release (Version 2.0.0) address this issue by collapsing toolbar buttons in Guides, Plot Segments, and Scaffolds into dropdown menus for the screen that is not wide enough.
