### ISSUE TITLE
Sankey chart not displaying correctly in power bi

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#544]
**Describe the bug**
I created a sankey chart in charticulator web and when I import it to power bi either as a template or custom visual, it displays only 3 levels instead of 4.

**To Reproduce**
Check the attached files

**Expected behavior**
I was expecting to see all the level

Files can be downloaded here: 
http://curbaldc.synology.me:5000/?launchApp=SYNO.SDS.Drive.Application&launchParam=file_id%3D548962676921901062

![charticulator pbi](https://user-images.githubusercontent.com/19476550/119366689-81eda300-bcb1-11eb-9b2a-04c74213457f.jpg)
![charticulator web](https://user-images.githubusercontent.com/19476550/119366698-831ed000-bcb1-11eb-9d09-09e6c22a1948.jpg)

Grab file number 7

**Comment by dm-p** [comment]
This one has been bugging me for a while too, so I've sat down and tried to crack it. I couldn't use @ruthpozuelo's example files as they seem to be behind a login process, so Ruth, hopefully you can appropriate and adapt what I've found out for the [Greenhouse Gas Emissions Sample](https://charticulator.com/gallery/world_greenhouse_gas_emissions.html). This has the same issue, if the data files are imported as-is: it will work on the Charticulator web app, but not in Power BI, and we just get the first three categories rather than all four:

![image](https://user-images.githubusercontent.com/10572054/119592691-0fa1cd80-be2d-11eb-8f67-6071ec03da59.png)

The issue stems from the fact that Power BI visuals can only support a single dataset, whereas the app appears to be able to treat them independently and resolve them as expected.

This is resolved in Power BI, by creating additional records in the dataset for the final links. These have a `source_id` matching the `target_id` of the incoming link.

For the example, I just needed to add the following four records to the links dataset:

| `source_id` | `target_id` |
| ---------- | ----------- |
| `CH4`         |  |
| `CO2` |  |
| `HFCs, PFCs, SF6` | |
| `N2O` |  |

And when I refresh, I can now see them in my links table when I add a column from the nodes table, e.g.:

![image](https://user-images.githubusercontent.com/10572054/119593087-b71f0000-be2d-11eb-935a-85ef785568b8.png)

And my chart also works :)

![image](https://user-images.githubusercontent.com/10572054/119592998-93f45080-be2d-11eb-89bb-ca61c6877071.png)

I think that ultimately, [the Power BI-specific doc for links](https://charticulator.com/docs/using-in-power-bi.html#chart-with-links) needs updating to mention this requirement.

Hopefully this can work for other similar scenarios 🙂

**Comment by zBritva** [comment]
Enabling "Show items with no data" for links columns should be enough to resolve this issue

**Comment by ruthpozuelo** [comment]
@zBritva  , showing items with no data did not fix it. 
I saw now that you can attach zip, so here are the files-
[Charticulator #7 Sankey chart.zip](https://github.com/microsoft/charticulator/files/6544564/Charticulator.7.Sankey.chart.zip)

**Comment by ruthpozuelo** [comment]
> This one has been bugging me for a while too, so I've sat down and tried to crack it. I couldn't use @ruthpozuelo's example files as they seem to be behind a login process, so Ruth, hopefully you can appropriate and adapt what I've found out for the [Greenhouse Gas Emissions Sample](https://charticulator.com/gallery/world_greenhouse_gas_emissions.html). This has the same issue, if the data files are imported as-is: it will work on the Charticulator web app, but not in Power BI, and we just get the first three categories rather than all four:
> 
> ![image](https://user-images.githubusercontent.com/10572054/119592691-0fa1cd80-be2d-11eb-8f67-6071ec03da59.png)
> 
> The issue stems from the fact that Power BI visuals can only support a single dataset, whereas the app appears to be able to treat them independently and resolve them as expected.
> 
> This is resolved in Power BI, by creating additional records in the dataset for the final links. These have a `source_id` matching the `target_id` of the incoming link.
> 
> For the example, I just needed to add the following four records to the links dataset:
> 
> `source_id`	`target_id`
> `CH4`	
> `CO2`	
> `HFCs, PFCs, SF6`	
> `N2O`	
> And when I refresh, I can now see them in my links table when I add a column from the nodes table, e.g.:
> 
> ![image](https://user-images.githubusercontent.com/10572054/119593087-b71f0000-be2d-11eb-935a-85ef785568b8.png)
> 
> And my chart also works :)
> 
> ![image](https://user-images.githubusercontent.com/10572054/119592998-93f45080-be2d-11eb-89bb-ca61c6877071.png)
> 
> I think that ultimately, [the Power BI-specific doc for links](https://charticulator.com/docs/using-in-power-bi.html#chart-with-links) needs updating to mention this requirement.
> 
> Hopefully this can work for other similar scenarios 🙂

It worked thanks!!

**Comment by nadiafank** [comment]
Hi,
I had faced a similar problem but unfortunately I don't remember much of
the details of the process. It's been a year now 😌
To relate, group and display the status of a number of my client's
projects.
The screenshot shows two Charticulator components in PBI: sankey and funnel.
Attached are the data tables (hierarchies) and ball sizes.

PS: Hi Daniel, for this visualisation I had asked you some questions at the
time ;)

[image: Charticulator_charts (sankey & Funnel).png]

[image: Charticulator_table_PBI.png]

[image: Charticulator_data.png]
