### ISSUE TITLE
Charticulator not showing when working without internet

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#583]
**Describe the bug**
Working without internet, causes the charticulator icon to disappear and the visual does not display.

**To Reproduce**
1. Create a charticulator chart
2. Disconnect internet.

**Expected behavior**
I would expect the visual icon to still be there and the visual to maybe have a text stating that internet connection is needed? The same happens with Bing maps in power bi, maybe do the same as them?

**Comment by dm-p** [comment]
I believe that that is a Power BI issue rather than a Charticulator issue, as I can replicate with any AppSource visual. Power BI has a cache of visuals it knows it should try to get the latest version of from AppSource and this usually falls back to the version in the .pbix if it can't connect, so something may have changed here recently. 

In this case the Charticulator code is not even being loaded by Power BI so would be hard to mitigate within the visual.

**Comment by ruthpozuelo** [comment]
oh, I only use Microsoft's custom visuals so I was not aware.
One thing though, Bing maps needs internet to work.  Does that work because it is built in  power bi?

**Comment by dm-p** [comment]
Anything I can offer here is purely speculative, as I'm just someone who knows the limitations and features of the custom visuals SDK.

In the case of Bing maps, it's a core visual and as such is likely not subject to the same rules as custom visuals. I would assume that core code can pretty much do whatever, as it's managed by the Power BI team.

Mapping visuals typically load their tiles and other data from remote resources remotely rather than storing them in-app. This is typically why you don't see any AppSource mapping visuals that are certified, as to be certified you cannot load any resources from an external location.

Even visuals published by MS through AppSource run on the same custom visuals platform that third party developers such as myself use to develop visuals, and as such have to work within the same constraints.

**Comment by ruthpozuelo** [comment]
Makes sense Daniel, thanks for sharing!
