### ISSUE TITLE
Click on axis label will filter in Power BI

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#718]
**Is your feature request related to a problem? Please describe.**
In Power Bi you can click on an axis text label (for example cook islands in the image below) and it will filter everything else, like the table besides the dumbell chart. 

It would be great if we could do the same in charticulator.
I understand that I can click on the elements and filter, but for what I can see, it doesnt work with axis labels.

![image](https://user-images.githubusercontent.com/19476550/131525974-20325ed3-c977-485d-b119-40678c47b41f.png)

**Comment by bongshin** [comment]
@ruthpozuelo If you create the Area label using the Text mark instead of assigning the Area data field to the Y-axis, you can click on the Area label to filter other visuals (e.g., table) on the page.

![image](https://user-images.githubusercontent.com/9288805/134779647-2a1cc91b-80d8-4f0a-aac1-e1333c64a20f.png)

![image](https://user-images.githubusercontent.com/9288805/134779894-5f3d8125-f8f3-4df5-9a64-c77e467e4b06.png)

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.2.1).
