### ISSUE TITLE
Transparency setting for all color elements

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#765]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to set the "color" transparent to all elements you can color by either adding the "color" transparent #000000ff or maybe an opacity setting?

**Describe the solution you'd like**
For example, I would like to be able to set the axis transparent (in this case it would have worked if the axis would be behind the element-great if we can set that too:
![image](https://user-images.githubusercontent.com/19476550/135593015-2e8c052c-d881-42b9-804a-864315133ba4.png)

**Comment by bongshin** [comment]
This issue is addressed in the recent release (Version 1.2.0). 

We introduced the "On Top" checkbox (as the the axis visibility option), which can be used to bring the axis to front or send it to back. 

![image](https://user-images.githubusercontent.com/9288805/142011050-b65c40b8-195e-453e-bd61-59da6e9b534d.png)
