### ISSUE TITLE
AutoMin and AutoMax don´t work anymore

### ISSUE THREAD

**Issue by AndreBI19** [microsoft/charticulator#827]
Hello, after the last update on 03/11, the propriety of automax and automix in X axis don´t work anymore. I have several damages because of this issue. Please, how a fix that?

**Screenshots**
![image](https://user-images.githubusercontent.com/93672276/140329667-5ef9fd06-0242-4fa9-8ff5-583c6413eccc.png)
![image](https://user-images.githubusercontent.com/93672276/140329747-dd5cf914-b1a9-4e0b-a39a-95f3fafe6363.png)

**Comment by tokleine** [comment]
Can confirm this issue. However in my polar plot the angular values still adjust properly, the radial values do not auto-scale. I can use standard PowerBI slicers to filter the data in the visual, but the radial axis in my visual remains unchanged.

All values
![image](https://user-images.githubusercontent.com/57629009/141102311-54106197-fed1-4abc-9222-008549bc2533.png)

Filtered
![image](https://user-images.githubusercontent.com/57629009/141102642-bdd30047-c6c3-48d0-92bc-31ed1a30cc74.png)

**Comment by AndreBI19** [comment]
Please, something?

**Comment by AndreBI19** [comment]
I lost two important charts because of this issue

**Comment by bongshin** [comment]
It seems that this bug is introduced in Version 1.1.2. We fixed this bug, but it will take time for the fix to become available. If you don't need recent updates, one solution is to use the earlier version of the visual (i.e., [Version 1.1.1](https://1drv.ms/u/s!Ankr3rcytXCwhKE_XC7LiFOVo1vllQ?e=DYnNC0)): you can find the instruction on how to import the visual from a local file at https://docs.microsoft.com/en-us/power-bi/developer/visuals/submission-testing.

**Comment by tokleine** [comment]
Thanks for the download link. I haven't tried opening or installing it yet as company policy does not allow this. It would thus be great if you could make these files available as an official release (incl a checksum) via the GitHub page. This would certainly inspire more trust than a private onedrive link :-)

**Comment by zBritva** [comment]
@tokleine `https://appsource.powerbi.com/charticulator.charticulator58556A88422D44A99D9BF0052B958F87.[VERSION].0.pbiviz ` there is link to appsource

**Comment by tokleine** [comment]
Great, thanks!

**Comment by AndreBI19** [comment]
Thank you!

**Comment by AndreBI19** [comment]
1.1.1 dont resolved the problem...

**Comment by bongshin** [comment]
@AndreBI19 Have you tried to flip back & forth between pages (i.e., go to a different page and come back to the one with the Charticulator visual) after you imported the visual from a local file? (If you have only one page, you need to create another page.) Power BI doesn't automatically update the visual when you import it.

**Comment by tokleine** [comment]
@bongshin thanks for this tip. However with v1.1.1 I am still running into an issue. When updating the radial axis setting to use auto min and auto max, if I already filtered my data before editing the visual, I can see that the visual (in the editor) updates, but when I click save in the visual editor and go back to the report page, I am promted with this (see screenshot) and I clicking on "Save" has no effect. Clicking on "Dont save" works...

![image](https://user-images.githubusercontent.com/57629009/141794023-9f179030-65a5-40c7-9d6f-c726f315b797.png)

**Comment by zBritva** [comment]
@tokleine it sounds similar to https://github.com/microsoft/charticulator/issues/821. Try to remove tooltips before save the chart. See https://github.com/microsoft/charticulator/issues/821#issuecomment-963548155.

**Comment by tokleine** [comment]
@zBritva removing the tooltips indeed helped, thanks. 

For anyone stumbling on this thread in the future: once you close PowerBI, it auto-disables the Developmode (https://docs.microsoft.com/en-us/power-bi/developer/visuals/submission-testing; File -> Options & Settings -> Options -> Report Settings -> "Turn on developer mode for this sessions") after you close the report and then reloads the new visual version from the AppSource/Marketplace. I almost overlooked this.

From my side, this issue should remain open until fixed with a new release, but my problem is solved/triaged for now. Thanks a lot for the fast response!

**Comment by AndreBI19** [comment]
Guys, thanks for the solution presented, but it still doesn't solve the problem for me. If I could keep developer mode active, I would be able to keep charts created in my reports. We can leave this topic as pending, right? The problem needs a definitive solution.

**Comment by bdarbonneau** [comment]
Turning to developper mode and reverting to v 1.1.1 restored the expected autoscale behaviour.
Hoping this issue will be resolved soon with a new version from the AppSource/Marketplace.

**Comment by tokleine** [comment]
Is there any estimate when this issue will be fixed in a new version? At the moment, when I edit the affected reports, I have to do my edits, turn on developer mode, import the local visual source file, adjust the visual settings, save and commit, publish. 
When I close the report, I have to do all of this again, just to adjust e.g. a filter.. Quite time consuming

**Comment by bongshin** [comment]
We are informed that, due to the Thanksgiving holiday, all deployments were blocked last week. The latest version (v1.2.1) is expected to reach the CDN this coming Wednesday (Dec 8).

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.2.1).
