### ISSUE TITLE
Export to Power BI Visual no longer working

### ISSUE THREAD

**Issue by zorgath** [microsoft/charticulator#865]
Exporting a Power BI Visual (PBVIZ) no longer produces a file that works in Power BI. It only produces a white visual with a auto generated title.

**To Reproduce**
1. Create Chart
2. Save Chart
3. Export Chart to PBI
4. Import custom visual to PBI 
5. Add data fields
6. Visual is now just white with the exception of the auto generated title.

**Expected behavior**
To see data. 

**Screenshots**

Bottom right side of Image. Chart Now only shows auto generated title. The rest of the screen is blank.

![image](https://user-images.githubusercontent.com/228115/144658172-8f178dd7-a788-4761-b690-e04b6bb48c47.png)

Not working PBVIZ is attached.
[Not Working.zip](https://github.com/microsoft/charticulator/files/7651618/Not.Working.zip)

My old pbviz file still works. I deleted the chart in PBI and created it again.
![image](https://user-images.githubusercontent.com/228115/144658213-80ae6f67-77b1-4e79-8cde-8dd57916489c.png)

Working PBVIZ is attached.
[Working.zip](https://github.com/microsoft/charticulator/files/7651616/Working.zip)
(Rename zip to pbviz)

**Diagnostic information**

Using 
Power BI Report Server May 2020
Power BI Desktop May 2020 Version
Also tested on Power BI Desktop September 2021

**Additional context**
Previously saved charts that have exported and worked, no longer work.
I have made sure things are marked as Do Not Summarize. I have made sure the sorting makes sense.
I tried it with multiple chart types.
There are no differences between the template files. (Attached)
[Chart (2).txt](https://github.com/microsoft/charticulator/files/7651689/Chart.2.txt)
(rename the .txt to .tmplt)

**Comment by doubleamp** [comment]
The same happens to me. I have tried to roll back to the previous commit (0b575ff8b462cf778de475b156bf7cc74808a6ad) in my local development environment, but it hasn't worked either.

**Comment by doubleamp** [comment]
zBritva's fix indeed solves the exporting problem for me. Thank you so much!

**Comment by bongshin** [comment]
This issue is addressed in the latest deployment. 

Please try to use the [Charticulator Visual](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200002793?tab=Overview). The Power BI extension of Charticulator, which is a different codebase, is _**not**_ actively maintained. Because we are a small team and have limited development resources, we focus on improving the Charticulator visual.

To learn how to get started, visit the [Charticulator Visual page](https://charticulator.com/docs/charticulator-visual.html).
