### ISSUE TITLE
Shape visibility is not taking effect

### ISSUE THREAD

**Issue by ACVida** [microsoft/charticulator#867]
I’ve created a custom visual called a Safety Cross and I’ve encountered an issue regarding shape visibility.  

![Safety Cross1](https://user-images.githubusercontent.com/96021364/145739173-d4214fa8-113b-40be-b0bd-5f67acdd8603.PNG)

So this visual is mostly working fine, except that the visibility status of a shape is not taking effect. This is how it looks like in the desktop:

![Safety Cross2](https://user-images.githubusercontent.com/96021364/145739394-ad8866cf-3f91-42b3-a6b1-4b98b7f08eb9.PNG)

The goal of the custom visual is to display the days of the month in a cross layout. Since some months have 28, 29, 30 or 31 days, days not present in the selected month should be hidden. I configured the custom visual by passing three Boolean fields included in the Safety Cross dataset: 
•	day_29_visible
•	day_30_visible
•	day_31_visible
These fields are then used by the custom visual, where the visibility attribute of the shapes referring to days 29, 30, 31 have been assigned with these values. You can open the file “Safety Falls.tmplt” in the zip file to check this configuration.

To replicate the issue,  open the pbix file included in the zip file, go to the Safety Cross page, where you can filter either by Feb, Mar or Apr 2021. Choosing February does not hide day 29, 30 and 31 and choosing Apr does not hide day 31 in the custom visual on the left.

There is a matrix on the right to display the values being passed to the Safety Cross custom visual on its left. 
 
I have also attached the PBI file, the template file and the pbiviz file.

[Safety Cross.zip](https://github.com/microsoft/charticulator/files/7700370/Safety.Cross.zip)

**Comment by bongshin** [comment]
The conditional visibility is for the marks used (in the _Glyph Editor_) to create a glyph, which is a visual representation of a single data row. To create the chart above, I suggest the data table be formatted the following way, which includes the columns (i.e., Xpos and Ypos) to position each glyph:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/9288805/146686623-aba46078-486e-4c20-80f4-6167c5be1cf7.png">

If you use the Charticulator visual with the Slicer and the data in the above format, you don't need to use the conditional visibility.
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/9288805/146686897-1d7359bc-51d7-4a3f-af77-ac97dacf4881.png">

Here is the pbix and csv files created with your data: [Safety Cross Test.zip](https://github.com/microsoft/charticulator/files/7741348/Safety.Cross.Test.zip).


Please note that the Power BI extension of Charticulator, which is a different codebase, is **_not_** actively maintained. Because we are a small team and have limited development resources, we focus on improving the Charticulator visual. If you want to see Charticulator further developed and eventually integrated into Power BI Desktop, please add your vote to this idea, [Microsoft Idea  · Integrate Charticulator into Power BI Desktop](https://ideas.powerbi.com/ideas/idea/?ideaid=6d7d6592-3aff-4b83-a4cf-806b593fc841).

**Comment by ACVida** [comment]
Thank you, I think that is the better way.
When opened the zipped pbix file, it looks like the Ypos values are  being treated as string instead of number. The sorting is off if you see below, where 31 is at the upper left corner instead of being at the bottom. Also the month is the previous one.

![image](https://user-images.githubusercontent.com/96021364/148861661-cec4ea34-446c-44ad-b333-95a725ce2b5c.png)

But I can see your copy above is displaying correctly. Is there a setting that I need to change?
There is no effect even if I have upgraded to the latest version of PBI desktop and to the Charticulator visual.

**Comment by ACVida** [comment]
I would prefer using the Charticulator visual if its the more actively maintained version. However, publishing it is an issue. It is not rendered properly, and need to be manually added by an admin to the "My Organization" page. 

![image](https://user-images.githubusercontent.com/96021364/148863825-fa847b61-9bb2-487b-b6c7-49bf7bd85f4d.png)

How can an admin add the Charticulator visual even if I can't export a pbiviz file or template from it?

**Comment by zBritva** [comment]
@ACVida you need to download *.pbiviz file of Charticulator visual [from Appsource page](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200002793?tab=Overview) then [import into Organizational](https://docs.microsoft.com/en-us/power-bi/admin/organizational-visuals#organizational-visuals) visual for your tenant
