### ISSUE TITLE
Text color formatting does not persist when exported as a PBI viz.

### ISSUE THREAD

**Issue by snapperlux** [Microsoft/charticulator#99]
Text mark colors revert back to default once exported as a PBI visual.
Charticulator:
![screenshot 315](https://user-images.githubusercontent.com/43861167/46495787-32d66500-c7cb-11e8-857b-99e1055a2834.png)

Power BI:
![screenshot 314](https://user-images.githubusercontent.com/43861167/46495810-3d90fa00-c7cb-11e8-8024-0cad808729b7.png)

**Comment by stopyoukid** [comment]
I just tried this and it seems to be working.  One thing that might be happening with your situation is that the color scale's domain is off, possibly because a different dataset was used to create the original chart.  You can try adjusting the domain by going to the formatting options in PowerBI, under "Charticulator".  There should be a way to set the min/max values of your dataset.

![image](https://user-images.githubusercontent.com/2513737/46619683-90262b00-cad7-11e8-9cf5-b081d13374c4.png)

If this does not fix your issue, would you kindly provide detailed steps on how you created this chart?

**Comment by snapperlux** [comment]
I used the exact data set in PBI that i used in Charticulator and still got the same results.

Steps to reproduce:
1. Add TEXT mark to Glyph
![step1](https://user-images.githubusercontent.com/43861167/46637560-989b5780-cb11-11e8-9d70-12ff3e27ac02.png)

2. Added Dimension field (SeverityName) to "text" section of glyph
![step 2](https://user-images.githubusercontent.com/43861167/46637569-9fc26580-cb11-11e8-9e63-93d46b790251.png)

3. Added Dimension field (SeverityName) to "color" section of glyph
![step 3](https://user-images.githubusercontent.com/43861167/46637573-a4871980-cb11-11e8-8614-6d7a9bbbcc89.png)

4. Select a specifc color for each distinct value of the SeverityName dimension  field.
![step 4](https://user-images.githubusercontent.com/43861167/46637576-a81aa080-cb11-11e8-993f-5ab3c687bcf5.png)

5. Export to PBI

Now, I did just notice it works if you do not select "Auto domain and range for Scale1".
Although, if you leave the box ticked when you export then the default Charticulator colors (wrong) will appear in PBI.
